name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: jenseng/dynamic-uses@v1
        with:
          uses: pantos-io/e2e-testing/.github/actions/run-tests@${{ github.repository == 'pantos-io/e2e-testing' && github.ref || 'main' }}
