name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: jenseng/dynamic-uses@v1
        with:
          uses: ${{ github.repository }}/.github/actions/run-tests@${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'main' }}
