name: Run E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
    setup-runner:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Registration Token
              id: get_registration_token
              run: |
                registration_token=$(gh api --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/pantos-io/e2e-testing/actions/runners/registration-token | jq -r .token)
                  echo "REGISTRATION_TOKEN=$registration_token" >> $GITHUB_OUTPUT
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.5.7
              
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: eu-west-1
                role-to-assume: ${{ secrets.AWS_ROLE }}
                role-session-name: OIDCSession
                
            - name: Run terraform init
              run: |
                cd self-hosted-runner 
                terraform init \
                  -backend-config "bucket=pantos-staging-environment-data" \
                  -backend-config "region=eu-central-1" \
                  -backend-config "key=terraform-state-file/self-hosted-runner.tfstate" \
                  -backend-config "dynamodb_table=terraform-state-lock-table" \
                  -backend-config "encrypt=true" \
                  -reconfigure

            # - name: Test
            #   run: echo ${{ steps.get_registration_token.outputs.REGISTRATION_TOKEN }}
            #TODO: Checkout repo, get the token, spin up Ec2
