name: Run E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
    setup-runner:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get Registration Token
              run: |
                registration_token=$(gh api --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/pantos-io/e2e-testing/actions/runners/registration-token | jq -r .token)
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            - name: Test
              run: echo $registration_token
            #TODO: Checkout repo, get the token, spin up Ec2
